baseURL = "https://victoriajanehughes.com"
languageCode = "en-gb"
title = "Vicky Hughes"
publishdir = "dist"
copyright = "© 2019 Vicky Hughes."
assetdir = "."
pluralizelisttitles = false
sectionPagesMenu = "main"
googleAnalytics = "UA-142187310-1"

[params]
contactEmail = "vicky.hughes@hotmail.com"
fontConfig = "Raleway|Libre+Franklin"
dateformat = "Jan 2, 2006"

[params.banner]
text = "Shop on Etsy"
link = "https://www.etsy.com/uk/shop/VictoriaIllustration"

[params.unpkg]
css = [
	"normalize.css/normalize.css"
]

[params.social]
instagram = "https://instagram.com/vickymadethis"
etsy = "https://www.etsy.com/uk/shop/VictoriaIllustration"
pinterest = "https://www.pinterest.co.uk/vickymadethis"

[[menu.main]]
identifier = "portfolio"
url = "/portfolio/"
weight = 1

[[menu.main]]
identifier = "about"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "contact"
url = "/contact/"
weight = 3
