baseURL = "https://vickyhughes.co.uk"
languageCode = "en-gb"
title = "Vicky Hughes"
copyright = "© 2019–2020 Vicky Hughes."
assetdir = "."
pluralizelisttitles = false
sectionPagesMenu = "main"
googleAnalytics = "UA-142187310-1"

[params]
contactEmail = "vicky.hughes@hotmail.com"
fontConfig = "Montserrat"
dateformat = "Jan 2, 2006"

## Uncomment to enable the top banner.
# [params.banner]
# text = "Shop on Etsy"
# link = "https://www.etsy.com/uk/shop/VictoriaIllustration"

[params.unpkg]
css = [
	"normalize.css/normalize.css"
]
js = [
	"imagesloaded@4/imagesloaded.pkgd.min.js",
	"masonry-layout@4/dist/masonry.pkgd.min.js"
]

[params.social]
instagram = "https://instagram.com/vickymadethis"
etsy = "https://www.etsy.com/uk/shop/VictoriaIllustration"
pinterest = "https://www.pinterest.co.uk/vickymadethis"

[[params.nav]]
identifier = "portfolio"
url = "/portfolio/"
weight = 1

[[params.nav]]
identifier = "about"
url = "/about/"
weight = 2

[[params.nav]]
identifier = "contact"
url = "/contact/"
weight = 3

[[params.nav]]
identifier = "shop"
url = "https://www.etsy.com/uk/shop/VictoriaIllustration"
weight = 4

[[params.nav]]
identifier = "store"
url = "/store/"
weight = 5

# Enable inline HTML in Markdown files (Hugo >0.64)
[markup.goldmark.renderer]
unsafe = true
