version: 2.1
orbs:
  slack: circleci/slack@2.5.1
jobs:
  build_deploy_notify:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - run: apk add --update nodejs nodejs-npm
      - run: npm ci
      - run: npm run prepare
      - run: hugo --minify
      - run: npm run deploy
      - slack/status:
          success_message: "$CIRCLE_PROJECT_REPONAME deployed"
          include_visit_job_action: false

workflows:
  version: 2
  build:
    jobs:
      - build_deploy_notify:
          context: slack-pushbot
