version: 2
jobs:
  build_deploy_notify:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - run: apk add --update nodejs nodejs-npm
      - restore_cache:
          keys:
            - nodemodules-{{ .Branch }}-{{ .Revision }}
            - nodemodules-{{ .Branch }}-
            - nodemodules-
      - run: npm ci
      - save_cache:
          key: nodemodules-{{ .Branch }}-{{ .Revision }}
          paths:
            - "node_modules"
      - run: npm run build
      - run: npm run deploy
      - run: curl -sS "https://api.telegram.org/bot$TELEGRAM_API_KEY/sendMessage?chat_id=$TELEGRAM_API_CHANNEL&text=$CIRCLE_PROJECT_REPONAME%20deployed%20%28$CIRCLE_BUILD_NUM%29" > /dev/null

workflows:
  version: 2
  build:
    jobs:
      - build_deploy_notify
